apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path:  /
            port: 80
            #initialDelaySeconds: 3
            #periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
            #initialDelaySeconds: 15
            #periodSeconds: 5
        env:
          - name: secret
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: password
      initContainers:
        - name: uday
          image: nginx:1.14.2
          command: ["echo" , "Hello Uday"]
          ports:
            - containerPort: 80
           
      