apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-storage-pv
  nameSpace: auth
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: host
  hostPath:
    path: /etc/data
    type: Directory
