apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
 name: all-access
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 name: all-binding
roleRef:
 kind: Role
 name: all-access
 apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "admin"
  apiGroup: rbac.authorization.k8s.io